import { CompletionItemKind, SymbolKind } from 'vscode-languageserver';
export declare namespace Kinds {
    namespace Symbol {
        const AnimationControllers: SymbolKind;
        const Animation: SymbolKind;
        const BlockCulling: SymbolKind;
        const Block: SymbolKind;
        const Effect: SymbolKind;
        const Entity: SymbolKind;
        const FakeEntity: SymbolKind;
        const Gamemode: SymbolKind;
        const Item: SymbolKind;
        const Objectives: SymbolKind;
        const Tickingarea: SymbolKind;
        const Event: SymbolKind;
        const Family: SymbolKind;
        const Functions: SymbolKind;
        const LootTable: SymbolKind;
        const Trading: SymbolKind;
        const Structure: SymbolKind;
        const Fogs: SymbolKind;
        const Texture: SymbolKind;
        const Materials: SymbolKind;
        const Models: SymbolKind;
        const Particle: SymbolKind;
        const RenderController: SymbolKind;
        const Sound: SymbolKind;
        const Boolean: SymbolKind;
        const Coordinate: SymbolKind;
        const Command: SymbolKind;
        const Float: SymbolKind;
        const Integer: SymbolKind;
        const Selector: SymbolKind;
        const Tag: SymbolKind;
        const Xp: SymbolKind;
        const Property: SymbolKind;
    }
    namespace Completion {
        const AnimationControllers: CompletionItemKind;
        const Animation: CompletionItemKind;
        const Block: CompletionItemKind;
        const Effect: CompletionItemKind;
        const Entity: CompletionItemKind;
        const FakeEntity: CompletionItemKind;
        const Gamemode: CompletionItemKind;
        const Item: CompletionItemKind;
        const Objectives: CompletionItemKind;
        const Tickingarea: CompletionItemKind;
        const Event: CompletionItemKind;
        const Family: CompletionItemKind;
        const Functions: CompletionItemKind;
        const LootTable: CompletionItemKind;
        const Trading: CompletionItemKind;
        const Structure: CompletionItemKind;
        const Fogs: CompletionItemKind;
        const Texture: CompletionItemKind;
        const Materials: CompletionItemKind;
        const Models: CompletionItemKind;
        const Particle: CompletionItemKind;
        const RenderController: CompletionItemKind;
        const Sound: CompletionItemKind;
        const Boolean: CompletionItemKind;
        const Coordinate: CompletionItemKind;
        const Command: CompletionItemKind;
        const Float: CompletionItemKind;
        const Integer: CompletionItemKind;
        const Selector: CompletionItemKind;
        const Tag: CompletionItemKind;
        const Xp: CompletionItemKind;
        const Vanilla: CompletionItemKind;
        const Property: CompletionItemKind;
    }
}
//# sourceMappingURL=kinds.d.ts.map