name: 📋 Test All

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group: {}
  workflow_dispatch: {}
  workflow_run: {}

env:
  FORCE_COLOR: true

jobs:
  build-and-test:
    name: 📋 Test on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v5

      - name: 🏗️ Setup Node.js Environment
        uses: actions/setup-node@v5
        with:
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 🏗️ Setup project
        run: npm ci

      - name: 🛠️ Build projects
        run: npm run compile

      - name: 📋 Run Tests
        run: npm run test:all

      - name: 🔍 Linting
        run: npm run lint
