name: 🚚 Release NPM Packages
on:
  workflow_dispatch: {}
  workflow_call: {}

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release-npm-packages:
    runs-on: ubuntu-latest
    environment:
      name: 'Package: ${{ matrix.package }}'
      url: https://www.npmjs.com/package/bc-minecraft-${{ matrix.package }}
    strategy:
      matrix:
        package:
          - bedrock-commands
          - bedrock-diagnoser
          - bedrock-project
          - shared
          - bedrock-types
          - bedrock-vanilla-data
          - molang
          - project
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v7

      - name: 🏗️ Setup Node.js Environment
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version-file: .nvmrc

      - name: 🏗️ Setup project
        run: npm ci

      - name: 🛠️ Build all packages
        run: npm run build

      - name: 🛠️ Build projects
        working-directory: '${{github.workspace}}/packages/${{matrix.package}}'
        run: npm run compile

      - name: 📋 Run Tests
        working-directory: '${{github.workspace}}/packages/${{matrix.package}}'
        run: npm run test

      - name: 🚚 Publish package
        working-directory: '${{github.workspace}}/packages/${{matrix.package}}'
        run: npm publish --tag latest
